name: Build and Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - dist/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          mkdir -p ~/.ssh/
          echo "${{ secrets.GH_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git remote set-url origin git@github.com:${{ github.repository }}.git

      - name: Push to GitHub
        run: |
          git add dist/**
          git commit -m "User script generating completed"
          git push