name: Build and Push

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Push build artifacts to PR branch
      run: |
        git config user.name "${{ secrets.GH_USERNAME }}"
        git config user.email "${{ secrets.GH_EMAIL }}"
        git checkout ${{ github.head_ref }}
        git add -A
        git commit -m "Add build artifacts"
        git push origin ${{ github.head_ref }}
